[tool.poetry]
inherit = "../../pyproject.toml"

[tool.poetry.name]
name = "hello_world"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"
jsonify = "0.5"

[tool.poetry.dev-dependencies]
pytest = "7.0.0"
