name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set PWD Environment Variable
      run: echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV


    - name: Create Environment File
      run: |
        cp .devcontainer/.env.ci .devcontainer/.env

    - name: Run Tests
      uses: devcontainers/ci@v0.3
      with:
        runCmd: pytest
    
    - name: Capture Docker Compose Logs
      if: failure() # Only run this step if previous steps failed
      run: |
        docker-compose --project-name monorepo-python-sample_devcontainer -f /home/runner/work/monorepo-python-sample/monorepo-python-sample/.devcontainer/docker-compose.yml logs

    - name: Archive Docker Copose Logs in Artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-compose-logs
        path: output/test/code-coverage.html
