name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Check out source repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
    
      - name: flake8 Lint
        uses: py-actions/flake8@v2

  testing:
    name: Run Test Suite
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set PWD Environment Variable
      run: echo "PWD=${GITHUB_WORKSPACE}" >> $GITHUB_ENV


    - name: Create Environment File
      run: |
        cp .devcontainer/.env.ci .devcontainer/.env

    - name: Run Tests
      uses: devcontainers/ci@v0.3
      with:
        runCmd: pytest